apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: petclinic-run-
spec:
  pipelineRef:
    name: maven-build
  resources:
  - name: app-git
    resourceSpec:
      type: git
      params:
        - name: url
          value: https://github.com/spring-projects/spring-petclinic
  workspaces:
    - name: local-maven-repo
      emptyDir: {}
    - name: shared-workspace
      persistentvolumeclaim:
        claimName: maven-repo-pvc
